import "dotenv/config";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CAL = path.resolve(
  __dirname,
  "../../../tools/browser-agent/data/content-calendar.json",
);
const SITE = "https://thepropertydna.com";
const TO = process.env.PREVIEW_TO || "stuartteamps@gmail.com";
const FROM = "Daniel Stuart | Stuart Team <hello@mail.thepropertydna.com>";

function esc(s: string) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function card(post: any) {
  const img = post.image || `${SITE}/social/photo/${post.date}.jpg`;
  const body = esc(post.text || "").replace(/\n/g, "<br>");
  return `
  <table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 28px;border:1px solid #e4d8c9;border-radius:8px;overflow:hidden;background:#fff;">
    <tr><td style="padding:10px 16px;background:#1f1a15;color:#fff;font:600 13px Arial;letter-spacing:1px;">IG / SOCIAL — ${post.date}</td></tr>
    <tr><td style="text-align:center;background:#000;"><img src="${img}" alt="${post.date}" style="max-width:340px;width:100%;display:block;margin:0 auto;"></td></tr>
    <tr><td style="padding:16px 18px;font:15px/1.6 Arial;color:#2c241d;">${body}</td></tr>
  </table>`;
}

async function run() {
  const dates = process.argv.slice(2);
  const cal = JSON.parse(fs.readFileSync(CAL, "utf8"));
  const posts = cal.posts.filter((p: any) =>
    dates.length ? dates.includes(p.date) : false,
  );
  if (!posts.length) {
    console.error("No posts matched dates:", dates);
    process.exit(1);
  }

  const html = `<!DOCTYPE html><html><body style="margin:0;background:#efe7dc;padding:24px;">
  <table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">
  <table width="560" cellpadding="0" cellspacing="0" style="max-width:560px;">
    <tr><td style="font:700 22px Georgia;color:#1f1a15;padding:0 0 6px;">Social post preview${dates.length > 1 ? "s" : ""}</td></tr>
    <tr><td style="font:14px Arial;color:#5a4e3f;padding:0 0 22px;">Review before posting. Reply "go" to approve, or tell me what to change.</td></tr>
    ${posts.map(card).join("")}
    <tr><td style="font:12px Arial;color:#9a8671;padding:8px 0 0;">Generated by PropertyDNA image-gen (gpt-image-1). Images served from ${SITE}/social/photo/.</td></tr>
  </table></td></tr></table></body></html>`;

  const subject = `Social preview — ${dates.join(", ")}`;
  const payload = JSON.stringify({ from: FROM, reply_to: TO, to: TO, subject, html });

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: payload,
  });
  const data = await res.json();
  console.log(`Resend ${res.status}:`, JSON.stringify(data));
  if (res.status >= 300) process.exit(1);
}

run().catch((e) => {
  console.error("FAILED:", e?.message || e);
  process.exit(1);
});
