import OpenAI from "openai";
import fs from "fs";
import path from "path";

const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export interface CreateSocialImageOptions {
  prompt: string;
  filename?: string;
  size?: "1024x1024" | "1024x1536" | "1536x1024";
  quality?: "low" | "medium" | "high";
  outputDir?: string;
}

export interface CreateSocialImageResult {
  filePath: string;
  filename: string;
  publicUrl?: string;
}

/**
 * Generate a luxury real estate editorial image via OpenAI gpt-image-1.
 *
 * Returns the local file path. Saves to /generated by default; pass
 * outputDir=app/frontend/public/social/ai to make the image web-accessible.
 */
export async function createSocialImage({
  prompt,
  filename = "social-image.png",
  size = "1024x1536",
  quality = "high",
  outputDir,
}: CreateSocialImageOptions): Promise<CreateSocialImageResult> {
  if (!process.env.OPENAI_API_KEY) {
    throw new Error("OPENAI_API_KEY not set in environment");
  }

  const result = await client.images.generate({
    model: "gpt-image-1",
    prompt,
    size,
    quality,
  });

  const imageBase64 = result.data?.[0]?.b64_json;
  if (!imageBase64) {
    throw new Error("No image returned from OpenAI");
  }

  const outDir = outputDir
    ? path.resolve(outputDir)
    : path.join(process.cwd(), "generated");
  fs.mkdirSync(outDir, { recursive: true });

  const filePath = path.join(outDir, filename);
  fs.writeFileSync(filePath, Buffer.from(imageBase64, "base64"));

  // If we wrote into the site's public/ tree, compute the eventual public URL
  let publicUrl: string | undefined;
  const publicRoot = "/Users/danstuart/propertydna-landing/app/frontend/public";
  if (filePath.startsWith(publicRoot)) {
    const rel = filePath.slice(publicRoot.length);
    publicUrl = `https://www.thepropertydna.com${rel}`;
  }

  return { filePath, filename, publicUrl };
}
