"""add profile timezone

Revision ID: 0ac05b74d053
Revises: 1a7e81bf0128
Create Date: 2026-07-23 00:59:47.211030
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

revision = '0ac05b74d053'
down_revision = '1a7e81bf0128'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tz', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='UTC'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('tz')

    # ### end Alembic commands ###
