"""add nutrition adjustment columns

Revision ID: 1a7e81bf0128
Revises: d08adad5da55
Create Date: 2026-07-23 00:52:29.502898
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

revision = '1a7e81bf0128'
down_revision = 'd08adad5da55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adjustment_kcal', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('adjustment_reasons', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_targets', schema=None) as batch_op:
        batch_op.drop_column('adjustment_reasons')
        batch_op.drop_column('adjustment_kcal')

    # ### end Alembic commands ###
