"""initial schema

Revision ID: d08adad5da55
Revises: 
Create Date: 2026-07-20 00:39:55.658322
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

revision = 'd08adad5da55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('exercises',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_muscle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('equipment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('external_auth_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_external_auth_id'), ['external_auth_id'], unique=False)

    op.create_table('ai_analysis_records',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_confidence', sa.Float(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analysis_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analysis_records_user_id'), ['user_id'], unique=False)

    op.create_table('cold_plunge_sessions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('session_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subjective_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cold_plunge_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cold_plunge_sessions_performed_at'), ['performed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cold_plunge_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('food_images',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_images_user_id'), ['user_id'], unique=False)

    op.create_table('goals',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('objective', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_user_id'), ['user_id'], unique=False)

    op.create_table('health_samples',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_samples_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_samples_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_samples_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_samples_user_id'), ['user_id'], unique=False)

    op.create_table('integrations',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_user_id'), ['user_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('stress', sa.Integer(), nullable=True),
    sa.Column('soreness', sa.Integer(), nullable=True),
    sa.Column('gratitude', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('daily_win', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('daily_challenge', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('voice_transcribed', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_user_id'), ['user_id'], unique=False)

    op.create_table('lab_results',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('panel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('test_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_low', sa.Float(), nullable=True),
    sa.Column('reference_high', sa.Float(), nullable=True),
    sa.Column('flag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('collected_on', sa.Date(), nullable=True),
    sa.Column('laboratory', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_document', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_results_user_id'), ['user_id'], unique=False)

    op.create_table('medications',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dose', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medications_user_id'), ['user_id'], unique=False)

    op.create_table('morning_routines',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('progression_week', sa.Integer(), nullable=False),
    sa.Column('intensity_target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_duration_min', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('morning_routines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_morning_routines_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_morning_routines_user_id'), ['user_id'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('morning_summary', sa.Boolean(), nullable=False),
    sa.Column('workout_reminder', sa.Boolean(), nullable=False),
    sa.Column('meal_reminder', sa.Boolean(), nullable=False),
    sa.Column('protein_deficit', sa.Boolean(), nullable=False),
    sa.Column('hydration_deficit', sa.Boolean(), nullable=False),
    sa.Column('bedtime', sa.Boolean(), nullable=False),
    sa.Column('journal_reminder', sa.Boolean(), nullable=False),
    sa.Column('recovery_warning', sa.Boolean(), nullable=False),
    sa.Column('weekly_report', sa.Boolean(), nullable=False),
    sa.Column('lab_followup', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quiet_hours_end', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('nutrition_targets',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Integer(), nullable=False),
    sa.Column('carbs_g', sa.Integer(), nullable=False),
    sa.Column('fat_g', sa.Integer(), nullable=False),
    sa.Column('fiber_g', sa.Integer(), nullable=False),
    sa.Column('hydration_ml', sa.Integer(), nullable=False),
    sa.Column('bmr', sa.Integer(), nullable=False),
    sa.Column('tdee', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.JSON(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nutrition_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nutrition_targets_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_nutrition_targets_user_id'), ['user_id'], unique=False)

    op.create_table('profiles',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('goal_weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('training_experience', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weekly_training_days', sa.Integer(), nullable=True),
    sa.Column('dietary_preferences', sa.JSON(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('injuries', sa.JSON(), nullable=True),
    sa.Column('medical_restrictions', sa.JSON(), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('wake_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bedtime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('units', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consent_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('readiness_scores',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('band', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('data_completeness', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('readiness_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readiness_scores_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_readiness_scores_user_id'), ['user_id'], unique=False)

    op.create_table('recovery_sessions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_sessions_performed_at'), ['performed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('sauna_sessions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('session_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subjective_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sauna_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sauna_sessions_performed_at'), ['performed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sauna_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('sleep_sessions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration_min', sa.Float(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('deep_min', sa.Float(), nullable=True),
    sa.Column('rem_min', sa.Float(), nullable=True),
    sa.Column('awake_min', sa.Float(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sleep_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_sessions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('supplements',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dose', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplements_user_id'), ['user_id'], unique=False)

    op.create_table('sync_jobs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('records_imported', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('workouts',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('perceived_effort', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dedup_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workouts_dedup_key'), ['dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_workouts_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workouts_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workouts_user_id'), ['user_id'], unique=False)

    op.create_table('calendar_events',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('calendar_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('matched_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('imported_workout_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['imported_workout_id'], ['workouts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_start_at'), ['start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_user_id'), ['user_id'], unique=False)

    op.create_table('meals',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eaten_at', sa.DateTime(), nullable=False),
    sa.Column('image_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['food_images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meals_eaten_at'), ['eaten_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_meals_user_id'), ['user_id'], unique=False)

    op.create_table('routine_exercises',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('routine_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('block', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prescription', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('substitution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['morning_routines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routine_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routine_exercises_routine_id'), ['routine_id'], unique=False)

    op.create_table('runs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workout_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('avg_pace_min_km', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('cadence', sa.Integer(), nullable=True),
    sa.Column('zone2_min', sa.Float(), nullable=True),
    sa.Column('perceived_effort', sa.Integer(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_user_id'), ['user_id'], unique=False)

    op.create_table('workout_sets',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workout_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exercise_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('load_kg', sa.Float(), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('rest_sec', sa.Integer(), nullable=True),
    sa.Column('tempo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_pr', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_sets_workout_id'), ['workout_id'], unique=False)

    op.create_table('meal_items',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimated_quantity', sa.Float(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('user_corrected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_items_meal_id'), ['meal_id'], unique=False)

    op.create_table('nutrient_values',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meal_item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('sugar_g', sa.Float(), nullable=False),
    sa.Column('sodium_mg', sa.Float(), nullable=False),
    sa.Column('potassium_mg', sa.Float(), nullable=False),
    sa.Column('calcium_mg', sa.Float(), nullable=False),
    sa.Column('iron_mg', sa.Float(), nullable=False),
    sa.Column('magnesium_mg', sa.Float(), nullable=False),
    sa.Column('vitamin_a_ug', sa.Float(), nullable=False),
    sa.Column('vitamin_c_mg', sa.Float(), nullable=False),
    sa.Column('vitamin_d_ug', sa.Float(), nullable=False),
    sa.Column('vitamin_b12_ug', sa.Float(), nullable=False),
    sa.Column('folate_ug', sa.Float(), nullable=False),
    sa.Column('cholesterol_mg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['meal_item_id'], ['meal_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nutrient_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nutrient_values_meal_item_id'), ['meal_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrient_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrient_values_meal_item_id'))

    op.drop_table('nutrient_values')
    with op.batch_alter_table('meal_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_items_meal_id'))

    op.drop_table('meal_items')
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_sets_workout_id'))

    op.drop_table('workout_sets')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_runs_started_at'))

    op.drop_table('runs')
    with op.batch_alter_table('routine_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_exercises_routine_id'))

    op.drop_table('routine_exercises')
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meals_user_id'))
        batch_op.drop_index(batch_op.f('ix_meals_eaten_at'))

    op.drop_table('meals')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_start_at'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_external_id'))

    op.drop_table('calendar_events')
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workouts_user_id'))
        batch_op.drop_index(batch_op.f('ix_workouts_started_at'))
        batch_op.drop_index(batch_op.f('ix_workouts_external_id'))
        batch_op.drop_index(batch_op.f('ix_workouts_dedup_key'))

    op.drop_table('workouts')
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_jobs_user_id'))

    op.drop_table('sync_jobs')
    with op.batch_alter_table('supplements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplements_user_id'))

    op.drop_table('supplements')
    with op.batch_alter_table('sleep_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sleep_sessions_date'))

    op.drop_table('sleep_sessions')
    with op.batch_alter_table('sauna_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sauna_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sauna_sessions_performed_at'))

    op.drop_table('sauna_sessions')
    with op.batch_alter_table('recovery_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_sessions_performed_at'))

    op.drop_table('recovery_sessions')
    with op.batch_alter_table('readiness_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readiness_scores_user_id'))
        batch_op.drop_index(batch_op.f('ix_readiness_scores_date'))

    op.drop_table('readiness_scores')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_user_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('nutrition_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_targets_user_id'))
        batch_op.drop_index(batch_op.f('ix_nutrition_targets_date'))

    op.drop_table('nutrition_targets')
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_user_id'))

    op.drop_table('notification_preferences')
    with op.batch_alter_table('morning_routines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_morning_routines_user_id'))
        batch_op.drop_index(batch_op.f('ix_morning_routines_date'))

    op.drop_table('morning_routines')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medications_user_id'))

    op.drop_table('medications')
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_results_user_id'))

    op.drop_table('lab_results')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_date'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_user_id'))
        batch_op.drop_index(batch_op.f('ix_integrations_provider'))

    op.drop_table('integrations')
    with op.batch_alter_table('health_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_samples_user_id'))
        batch_op.drop_index(batch_op.f('ix_health_samples_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_health_samples_metric'))
        batch_op.drop_index(batch_op.f('ix_health_samples_external_id'))

    op.drop_table('health_samples')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_user_id'))

    op.drop_table('goals')
    with op.batch_alter_table('food_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_images_user_id'))

    op.drop_table('food_images')
    with op.batch_alter_table('cold_plunge_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cold_plunge_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_cold_plunge_sessions_performed_at'))

    op.drop_table('cold_plunge_sessions')
    with op.batch_alter_table('ai_analysis_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analysis_records_user_id'))

    op.drop_table('ai_analysis_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_external_auth_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_name'))

    op.drop_table('exercises')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
