import { useState, useEffect } from 'react';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
import FadeUp from '@/components/FadeUp';

// PropertyDNA Market Truths — an INTERNAL content feed the growth agent publishes
// to daily. No external platform: content is generated by our own agent and
// served from our own domain (SEO-indexed), growing every day.
const GOLD = '#B89355', CREAM = '#F4F0E8', INK = '#0F0E0D';
type Insight = { slug: string; title: string; body: string; tweet: string; date: string };

export default function Insights() {
  const [items, setItems] = useState<Insight[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    document.title = 'Market Truths — Real Home-Pricing Intelligence | PropertyDNA';
    const d = 'Daily plain-truth insights on home pricing, overpriced listings, and the data agents hoped you\'d never see. Free, from PropertyDNA.';
    let tag = document.head.querySelector('meta[name="description"]') as HTMLMetaElement | null;
    if (!tag) { tag = document.createElement('meta'); tag.setAttribute('name', 'description'); document.head.appendChild(tag); }
    tag.content = d;
    fetch('/.netlify/functions/get-insights').then(r => r.json()).then(j => { setItems(j.insights || []); setLoading(false); }).catch(() => setLoading(false));
  }, []);

  return (
    <div style={{ background: INK, color: CREAM, minHeight: '100vh' }}>
      <Nav />
      <section style={{ padding: 'clamp(100px,12vw,140px) clamp(24px,6vw,80px) clamp(60px,8vw,100px)' }}>
        <div style={{ maxWidth: 760, margin: '0 auto' }}>
          <FadeUp>
            <span style={{ fontFamily: 'Jost, sans-serif', fontSize: 10, letterSpacing: '3px', textTransform: 'uppercase', color: GOLD }}>PropertyDNA · Market Truths</span>
            <h1 style={{ fontFamily: 'Cormorant Garamond, Georgia, serif', fontSize: 'clamp(38px,5.5vw,64px)', fontWeight: 300, lineHeight: 1.05, margin: '12px 0 16px' }}>
              The data agents hoped <em style={{ fontStyle: 'italic', color: GOLD }}>you'd never see.</em>
            </h1>
            <p style={{ fontFamily: 'Jost, sans-serif', fontSize: 17, lineHeight: 1.6, color: '#C9C3B6', maxWidth: 560 }}>
              Plain-truth intelligence on home pricing — published fresh every day. Then check any listing yourself:{' '}
              <a href="/price-check" style={{ color: GOLD }}>is it overpriced?</a>
            </p>
          </FadeUp>

          <div style={{ marginTop: 48 }}>
            {loading && <p style={{ fontFamily: 'Jost, sans-serif', color: '#7C766B' }}>Loading…</p>}
            {!loading && !items.length && (
              <p style={{ fontFamily: 'Jost, sans-serif', color: '#C9C3B6' }}>
                First insight publishes tomorrow morning. Meanwhile — <a href="/price-check" style={{ color: GOLD }}>check if a listing is overpriced →</a>
              </p>
            )}
            {items.map((it) => (
              <FadeUp key={it.slug}>
                <article style={{ borderTop: '1px solid #26241F', padding: '28px 0' }}>
                  <div style={{ fontFamily: 'Jost, sans-serif', fontSize: 11, letterSpacing: '2px', textTransform: 'uppercase', color: '#7C766B', marginBottom: 8 }}>{it.date}</div>
                  <h2 style={{ fontFamily: 'Cormorant Garamond, Georgia, serif', fontSize: 'clamp(24px,3.2vw,32px)', fontWeight: 400, margin: '0 0 12px', color: CREAM }}>{it.title}</h2>
                  <p style={{ fontFamily: 'Jost, sans-serif', fontSize: 16, lineHeight: 1.75, color: '#C9C3B6', whiteSpace: 'pre-wrap' }}>{it.body}</p>
                  <a href="/price-check" style={{ display: 'inline-block', marginTop: 14, fontFamily: 'Jost, sans-serif', fontSize: 13, letterSpacing: '1px', textTransform: 'uppercase', color: GOLD, textDecoration: 'none' }}>Check a listing →</a>
                </article>
              </FadeUp>
            ))}
          </div>
        </div>
      </section>
      <Footer />
    </div>
  );
}
